#!/bin/sh
render () {

   TexBase=$(basename "$1" ".tex")
   mkdir -p build/pdf
   cp -r source/* build/pdf

   cd build/pdf
   pdflatex "$2" "$TexBase.tex"  
   bibtex "$TexBase" 
   pdflatex "$2" "$TexBase.tex"  
   pdflatex "$2"  "$TexBase.tex"  
   #mupdf "$TexBase.pdf"
}
   
#render "forensic-tool-development-with-rust.tex" "-interaction=batchmode"
render "forensic-tool-development-with-rust.tex" 
